# Generated by Django 6.0 on 2025-12-30 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_sitio', models.CharField(default='5491155947837', help_text='Número de WhatsApp que aparece en el sitio (ej: 5491155947837)', max_length=20)),
                ('instagram', models.CharField(default='cami.zco', help_text='Usuario de Instagram (sin @)', max_length=100)),
                ('texto_boton_pedido', models.CharField(default='Hacé tu pedido', help_text='Texto del botón principal de pedidos', max_length=100)),
                ('banner_activo', models.BooleanField(default=False, help_text='Activar banner temporal')),
                ('banner_texto', models.CharField(blank=True, help_text="Texto del banner (ej: 'Pedidos cerrados por vacaciones')", max_length=200)),
                ('notas_internas_pedidos', models.BooleanField(default=True, help_text='Mostrar campo de notas internas en pedidos')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
        migrations.CreateModel(
            name='CTAFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='¿Querés un regalo personalizado?', max_length=200)),
                ('texto', models.TextField(blank=True, help_text='Texto opcional debajo del título')),
                ('texto_boton', models.CharField(default='Hacé tu pedido', max_length=50)),
                ('url_cta', models.CharField(default='/pedir/', help_text='URL del botón CTA (ej: /pedir/ o https://wa.me/5491112345678)', max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CTA Final',
                'verbose_name_plural': 'CTA Final',
            },
        ),
        migrations.CreateModel(
            name='GaleriaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='imagen')),
                ('titulo', models.CharField(blank=True, help_text='Título opcional para la imagen', max_length=200)),
                ('alt_text', models.CharField(help_text='Texto alternativo para accesibilidad', max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería de Trabajos',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HeroHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_fondo', models.ImageField(blank=True, help_text='Imagen de fondo del hero', null=True, upload_to='hero/', verbose_name='imagen_fondo')),
                ('logo', models.ImageField(blank=True, help_text='Logo de la marca', null=True, upload_to='logo/', verbose_name='logo')),
                ('titulo', models.CharField(default='Vasos Tallados Personalizados', max_length=200)),
                ('subtitulo', models.CharField(default='Diseños únicos para momentos especiales', max_length=300)),
                ('texto_boton', models.CharField(default='Hacé tu pedido', max_length=50)),
                ('url_cta', models.CharField(default='/pedir/', help_text='URL del botón CTA (ej: /pedir/ o URL completa)', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Hero Home',
                'verbose_name_plural': 'Hero Home',
            },
        ),
        migrations.CreateModel(
            name='PasoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, help_text='Emoji o código de icono (ej: ✨, 1, etc.)', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Paso del Proceso',
                'verbose_name_plural': 'Pasos del Proceso',
                'ordering': ['orden', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['orden', 'pregunta'],
            },
        ),
        migrations.CreateModel(
            name='SeccionHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nuestro_trabajo', 'Nuestro Trabajo'), ('proceso', 'Proceso'), ('testimoniales', 'Testimoniales'), ('otro', 'Otro')], default='nuestro_trabajo', max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Sección Home',
                'verbose_name_plural': 'Secciones Home',
                'ordering': ['orden', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_desde', models.BooleanField(default=False, help_text="Si está marcado, muestra 'Desde $X' en lugar del precio fijo")),
                ('tiempo_estimado', models.CharField(default='7-10 días', help_text="Ej: '7-10 días', '2 semanas'", max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False, help_text='Aparece en la home')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/', verbose_name='imagen')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Imágenes de Productos',
                'ordering': ['es_principal', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='ImagenSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proceso', 'Proceso de trabajo'), ('trabajo_real', 'Trabajo real'), ('logo', 'Logo'), ('persona_trabajando', 'Persona trabajando'), ('cliente', 'Cliente'), ('evento', 'Evento'), ('temporada', 'Temporada'), ('hero', 'Hero / Imagen principal'), ('otro', 'Otro')], default='proceso', max_length=20)),
                ('imagen', models.ImageField(upload_to='secciones/', verbose_name='imagen')),
                ('alt_text', models.CharField(help_text='Texto alternativo para accesibilidad', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.seccionhome')),
            ],
            options={
                'verbose_name': 'Imagen de Sección',
                'verbose_name_plural': 'Imágenes de Secciones',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
