# Generated by Django 6.0 on 2025-12-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL completa de Instagram (ej: https://instagram.com/cami.zco)'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='whatsapp_mensaje',
            field=models.CharField(blank=True, default='Hola! Quiero hacer un pedido 😊', help_text='Mensaje predefinido para WhatsApp', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='whatsapp_numero',
            field=models.CharField(blank=True, help_text='Número de WhatsApp solo con números (ej: 5491155947837)', max_length=20),
        ),
    ]
