# Generated by Django 6.0 on 2025-12-27 22:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_producto_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
