# Generated by Django 6.0 on 2025-12-27 22:53

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_alter_producto_fecha_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('nuestro_trabajo', 'Nuestro Trabajo'), ('proceso', 'Proceso'), ('testimoniales', 'Testimoniales'), ('otro', 'Otro')], default='nuestro_trabajo', max_length=20, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Sección Home',
                'verbose_name_plural': 'Secciones Home',
                'ordering': ['orden', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='ImagenSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('proceso', 'Proceso de trabajo'), ('trabajo_real', 'Trabajo real'), ('logo', 'Logo'), ('persona_trabajando', 'Persona trabajando'), ('cliente', 'Cliente'), ('evento', 'Evento'), ('temporada', 'Temporada'), ('otro', 'Otro')], default='proceso', max_length=20)),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('alt_text', models.CharField(help_text='Texto alternativo para accesibilidad', max_length=200)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('seccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='catalogo.seccionhome')),
            ],
            options={
                'verbose_name': 'Imagen de Sección',
                'verbose_name_plural': 'Imágenes de Secciones',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
