# Generated by Django 6.0 on 2025-12-27 23:00

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_seccionhome_imagenseccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='¿Querés un regalo personalizado?', max_length=200)),
                ('texto', models.TextField(blank=True, help_text='Texto opcional debajo del título')),
                ('texto_boton', models.CharField(default='Hacé tu pedido', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CTA Final',
                'verbose_name_plural': 'CTA Final',
            },
        ),
        migrations.CreateModel(
            name='GaleriaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
                ('titulo', models.CharField(blank=True, help_text='Título opcional para la imagen', max_length=200)),
                ('alt_text', models.CharField(help_text='Texto alternativo para accesibilidad', max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería de Trabajos',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HeroHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_fondo', cloudinary.models.CloudinaryField(blank=True, help_text='Imagen de fondo del hero', max_length=255, null=True, verbose_name='imagen_fondo')),
                ('logo', cloudinary.models.CloudinaryField(blank=True, help_text='Logo de la marca', max_length=255, null=True, verbose_name='logo')),
                ('titulo', models.CharField(default='Vasos Tallados Personalizados', max_length=200)),
                ('subtitulo', models.CharField(default='Diseños únicos para momentos especiales', max_length=300)),
                ('texto_boton', models.CharField(default='Hacé tu pedido', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Hero Home',
                'verbose_name_plural': 'Hero Home',
            },
        ),
        migrations.CreateModel(
            name='PasoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(blank=True, help_text='Emoji o código de icono (ej: ✨, 1, etc.)', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Paso del Proceso',
                'verbose_name_plural': 'Pasos del Proceso',
                'ordering': ['orden', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaFrecuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta Frecuente',
                'verbose_name_plural': 'Preguntas Frecuentes',
                'ordering': ['orden', 'pregunta'],
            },
        ),
        migrations.AlterField(
            model_name='imagenseccion',
            name='tipo',
            field=models.CharField(choices=[('proceso', 'Proceso de trabajo'), ('trabajo_real', 'Trabajo real'), ('logo', 'Logo'), ('persona_trabajando', 'Persona trabajando'), ('cliente', 'Cliente'), ('evento', 'Evento'), ('temporada', 'Temporada'), ('hero', 'Hero / Imagen principal'), ('otro', 'Otro')], default='proceso', max_length=20),
        ),
    ]
