# Generated by Django 6.0 on 2025-12-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_ctafinal_galeriatrabajo_herohome_pasoproceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herohome',
            name='url_cta',
            field=models.CharField(default='/pedir/', help_text='URL del botón CTA (ej: /pedir/ o URL completa)', max_length=200),
        ),
    ]
