# Generated by Django 6.0 on 2025-12-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_herohome_url_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctafinal',
            name='url_cta',
            field=models.CharField(default='/pedir/', help_text='URL del botón CTA (ej: /pedir/ o https://wa.me/5491112345678)', max_length=200),
        ),
    ]
