# Generated by Django 6.0 on 2025-12-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_ctafinal_url_cta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_sitio', models.CharField(default='5491155947837', help_text='Número de WhatsApp que aparece en el sitio (ej: 5491155947837)', max_length=20)),
                ('instagram', models.CharField(default='cami.zco', help_text='Usuario de Instagram (sin @)', max_length=100)),
                ('texto_boton_pedido', models.CharField(default='Hacé tu pedido', help_text='Texto del botón principal de pedidos', max_length=100)),
                ('banner_activo', models.BooleanField(default=False, help_text='Activar banner temporal')),
                ('banner_texto', models.CharField(blank=True, help_text="Texto del banner (ej: 'Pedidos cerrados por vacaciones')", max_length=200)),
                ('notas_internas_pedidos', models.BooleanField(default=True, help_text='Mostrar campo de notas internas en pedidos')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
