# Generated by Django 6.0 on 2025-12-30 01:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_destino', models.CharField(default='5491112345678', help_text='Número de WhatsApp para recibir pedidos (ej: 5491112345678)', max_length=20)),
                ('tiempo_entrega', models.CharField(default='7-10 días', help_text='Texto de tiempo estimado de entrega (ej: 7-10 días)', max_length=100)),
                ('tiempo_respuesta', models.CharField(default='24-48 horas', help_text='Tiempo estimado de respuesta por WhatsApp (ej: 24-48 horas)', max_length=100)),
                ('texto_confirmacion', models.TextField(blank=True, help_text='Texto opcional para la página de confirmación')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Pedidos',
                'verbose_name_plural': 'Configuración de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=20)),
                ('texto_tallar', models.TextField(blank=True, help_text='Texto que el cliente quiere tallar (opcional pero recomendado)')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_para_cuando', models.DateField(blank=True, help_text='¿Para cuándo lo necesitás?', null=True, verbose_name='Fecha para cuándo')),
                ('entrega', models.CharField(choices=[('retiro', 'Retiro'), ('envio', 'Envío')], default='retiro', max_length=10)),
                ('zona_ciudad', models.CharField(blank=True, help_text='Solo si elegiste envío', max_length=200, verbose_name='Zona / Ciudad')),
                ('notas', models.TextField(blank=True, help_text='Algo más a tener en cuenta')),
                ('notas_internas', models.TextField(blank=True, help_text='Notas internas (solo visible en el panel)')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('confirmado', 'Confirmado'), ('en_produccion', 'En producción'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='nuevo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_actualizacion', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('website', models.CharField(blank=True, help_text='Campo honeypot - no completar', max_length=200)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
