# Generated by Django 6.0 on 2025-12-27 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=20)),
                ('texto_tallar', models.TextField(help_text='Texto que el cliente quiere tallar')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_deseada', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales del cliente')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('confirmado', 'Confirmado'), ('en_produccion', 'En producción'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='nuevo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
