# Generated by Django 6.0 on 2025-12-28 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_destino', models.CharField(default='5491112345678', help_text='Número de WhatsApp para recibir pedidos (ej: 5491112345678)', max_length=20)),
                ('tiempo_entrega', models.CharField(default='7-10 días', help_text='Texto de tiempo estimado de entrega (ej: 7-10 días)', max_length=100)),
                ('tiempo_respuesta', models.CharField(default='24-48 horas', help_text='Tiempo estimado de respuesta por WhatsApp (ej: 24-48 horas)', max_length=100)),
                ('texto_confirmacion', models.TextField(blank=True, help_text='Texto opcional para la página de confirmación')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Pedidos',
                'verbose_name_plural': 'Configuración de Pedidos',
            },
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fecha_deseada',
        ),
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.CharField(choices=[('retiro', 'Retiro'), ('envio', 'Envío')], default='retiro', max_length=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_para_cuando',
            field=models.DateField(blank=True, help_text='¿Para cuándo lo necesitás?', null=True, verbose_name='Fecha para cuándo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='website',
            field=models.CharField(blank=True, help_text='Campo honeypot - no completar', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='zona_ciudad',
            field=models.CharField(blank=True, help_text='Solo si elegiste envío', max_length=200, verbose_name='Zona / Ciudad'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='notas',
            field=models.TextField(blank=True, help_text='Algo más a tener en cuenta'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='texto_tallar',
            field=models.TextField(blank=True, help_text='Texto que el cliente quiere tallar (opcional pero recomendado)'),
        ),
    ]
