# Generated by Django 6.0 on 2025-12-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_configuracionpedido_remove_pedido_fecha_deseada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas internas (solo visible en el panel)'),
        ),
    ]
